repos:
- repo: local
  hooks:
  - id: autoflake
    name: autoflake
    entry: pipenv run autoflake --remove-all-unused-imports --ignore-init-module-imports -ir .
    language: system
    pass_filenames: false

- repo: local
  hooks:
  - id: isort
    name: isort
    entry: pipenv run isort .
    language: system
    pass_filenames: false

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.5.1
  hooks:
  - id: mypy
    additional_dependencies: [types-requests, types-redis, types-pytz, types-filelock, types-python-dateutil]
    language_version: python3.9

- repo: https://github.com/psf/black
  rev: 23.9.1
  hooks:
  - id: black
    language_version: python3.9

- repo: https://github.com/pycqa/flake8
  rev: 5.0.4
  hooks:
  - id: flake8
    additional_dependencies: [
        flake8-fixme,
        flake8-print,
    ]
    language_version: python3.9
